theme: jekyll-theme-tactile
title: Simulation of Thunderstorm
description: A realistic 3D Simulation of a Thunderstorm

 
 
    <br />     
    <br />                       
                        Dhaval Chauhan, Akshay Sharma, Sanket Sheth
                      
                      
  <br />                Computer Science Department 
  
                      
 <br />                 Rochester Institute of Technology
